---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: apiscout
  name: apiscout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apiscout
  template:
    metadata:
      labels:
        run: apiscout
    spec:
      containers:
      - name: apiscout
        image:
        env:
        - name: MODE
          value: "KUBE"
        - name: HUGODIR
          value: "/tmp"
        - name: EXTERNALIP
          value: "192.168.99.100"
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: apiscout-svc
  name: apiscout-svc
  namespace: default
spec:
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 80
  selector:
    run: apiscout
  type: LoadBalancer