baseURL = "https://tibcosoftware.github.io/apiscout/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "API Scout :: Finding your APIs in Kubernetes"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = true

[params]
  editURL = ""
  description = "Documentation for API Scout"
  author = "API Scout"
  showVisitedLinks = false
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = true
  disableShortcutsTitle = true
  disableLanguageSwitchingButton = true
  ordersectionsby = "weight"
  themeVariant = "green"

[outputs]
home = [ "HTML", "RSS", "JSON"]
